# FILL DISTRICT

# 1. Автономна республіка Крим
INSERT INTO District VALUES (1, "Алушта, місто",1);
INSERT INTO District VALUES (2, "Бахчисарайський район",1);
INSERT INTO District VALUES (3, "Білогірський район",1);
INSERT INTO District VALUES (4, "Джанкойський район",1);
INSERT INTO District VALUES (5, "Євпаторія, місто",1);
INSERT INTO District VALUES (6, "Керч, місто",1);
INSERT INTO District VALUES (7, "Кіровський район",1);
INSERT INTO District VALUES (8, "Красногвардійський район",1);
INSERT INTO District VALUES (9, "Красноперекопський район",1);
INSERT INTO District VALUES (10, "Ленінський район",1);
INSERT INTO District VALUES (11, "Нижньогірський район",1);
INSERT INTO District VALUES (12, "Первомайський район",1);
INSERT INTO District VALUES (13, "Роздольненський район",1);
INSERT INTO District VALUES (14, "Сакський район",1);
INSERT INTO District VALUES (15, "Сімферополь, місто",1);
INSERT INTO District VALUES (16, "Сімферопольський район",1);
INSERT INTO District VALUES (17, "Совєтський район",1);
INSERT INTO District VALUES (18, "Судак, місто",1);
INSERT INTO District VALUES (19, "Феодосія, місто",1);
INSERT INTO District VALUES (20, "Чорноморський район",1);
INSERT INTO District VALUES (21, "Ялта, місто",1);

# 2. Вінницька область
INSERT INTO District VALUES (22, "Барський район",2);
INSERT INTO District VALUES (23, "Бершадський район",2);
INSERT INTO District VALUES (24, "Вінниця, місто",2);
INSERT INTO District VALUES (25, "Вінницький район",2);
INSERT INTO District VALUES (26, "Гайсинський район",2);
INSERT INTO District VALUES (27, "Жмеринський район",2);
INSERT INTO District VALUES (28, "Іллінецький район",2);
INSERT INTO District VALUES (29, "Калинівський район",2);
INSERT INTO District VALUES (30, "Козятинський район",2);
INSERT INTO District VALUES (31, "Крижопільський район",2);
INSERT INTO District VALUES (32, "Липовецький район",2);
INSERT INTO District VALUES (33, "Літинський район",2);
INSERT INTO District VALUES (34, "Могилів-Подільський район",2);
INSERT INTO District VALUES (35, "Мурованокуриловецький район",2);
INSERT INTO District VALUES (36, "Немирівський район",2);
INSERT INTO District VALUES (37, "Оратівський район",2);
INSERT INTO District VALUES (38, "Піщанський район",2);
INSERT INTO District VALUES (39, "Погребищенський район",2);
INSERT INTO District VALUES (40, "Теплицький район",2);
INSERT INTO District VALUES (41, "Тиврівський район",2);
INSERT INTO District VALUES (42, "Томашпільський район",2);
INSERT INTO District VALUES (43, "Тростянецький район",2);
INSERT INTO District VALUES (44, "Тульчинський район",2);
INSERT INTO District VALUES (45, "Хмільницький район",2);
INSERT INTO District VALUES (46, "Чернівецький район",2);
INSERT INTO District VALUES (47, "Чечельницький район",2);
INSERT INTO District VALUES (48, "Шаргородський район",2);
INSERT INTO District VALUES (49, "Ямпільський район",2);

# 3. Волинська область
INSERT INTO District VALUES (50, "Володимир-Волинський район",3);
INSERT INTO District VALUES (51, "Горохівський район",3);
INSERT INTO District VALUES (52, "Іваничівський район",3);
INSERT INTO District VALUES (53, "Камінь-Каширський район",3);
INSERT INTO District VALUES (54, "Ківерцівський район",3);
INSERT INTO District VALUES (55, "Ковельський район",3);
INSERT INTO District VALUES (56, "Локачинський район",3);
INSERT INTO District VALUES (57, "Луцьк, місто",3);
INSERT INTO District VALUES (58, "Луцький район",3);
INSERT INTO District VALUES (59, "Любешівський район",3);
INSERT INTO District VALUES (60, "Любомльський район",3);
INSERT INTO District VALUES (61, "Маневицький район",3);
INSERT INTO District VALUES (62, "Нововолинськ, місто",3);
INSERT INTO District VALUES (63, "Ратнівський район",3);
INSERT INTO District VALUES (64, "Рожищенський район",3);
INSERT INTO District VALUES (65, "Старовижівський район",3);
INSERT INTO District VALUES (66, "Турійський район",3);
INSERT INTO District VALUES (67, "Щацький район",3);

# 4. Дніпропетровська область
INSERT INTO District VALUES (68, "Апостолівський район",4);
INSERT INTO District VALUES (69, "Васильківський район",4);
INSERT INTO District VALUES (70, "Верхньодніпровський район",4);
INSERT INTO District VALUES (71, "Вільногірськ, місто",4);
INSERT INTO District VALUES (72, "Дніпродзержинськ, місто",4);
INSERT INTO District VALUES (73, "Дніпропетровськ, місто",4);
INSERT INTO District VALUES (74, "Дніпропетровський район",4);
INSERT INTO District VALUES (75, "Жовті води, місто",4);
INSERT INTO District VALUES (76, "Кривий ріг, місто",4);
INSERT INTO District VALUES (77, "Криворізький район",4);
INSERT INTO District VALUES (78, "Криничанський район",4);
INSERT INTO District VALUES (79, "Магдалинівський район",4);
INSERT INTO District VALUES (80, "Марганець, місто",4);
INSERT INTO District VALUES (81, "Межівський район",4);
INSERT INTO District VALUES (82, "Нікопольський район",4);
INSERT INTO District VALUES (83, "Новомосковський район",4);
INSERT INTO District VALUES (84, "Орджонікідзе, місто",4);
INSERT INTO District VALUES (85, "Павлоградський район",4);
INSERT INTO District VALUES (86, "Першотравенськ, місто",4);
INSERT INTO District VALUES (87, "Петриківський район",4);
INSERT INTO District VALUES (88, "Петропавлівський район",4);
INSERT INTO District VALUES (89, "Покровський район",4);
INSERT INTO District VALUES (90, "П'ятихатський район",4);
INSERT INTO District VALUES (91, "Синельниківський район",4);
INSERT INTO District VALUES (92, "Солонянський район",4);
INSERT INTO District VALUES (93, "Софіївський район",4);
INSERT INTO District VALUES (94, "Тернівка, місто",4);
INSERT INTO District VALUES (95, "Томаківський район",4);
INSERT INTO District VALUES (96, "Царичанський район",4);
INSERT INTO District VALUES (97, "Широківський район",4);
INSERT INTO District VALUES (98, "Юр'ївський район",4);

# 5. Донецька область
INSERT INTO District VALUES (99, "Амвросіївський район",5);
INSERT INTO District VALUES (100, "Артемівський район",5);
INSERT INTO District VALUES (101, "Великоновосілківський район",5);
INSERT INTO District VALUES (102, "Волноваський район",5);
INSERT INTO District VALUES (103, "Володарський район",5);
INSERT INTO District VALUES (104, "Горлівка, місто",5);
INSERT INTO District VALUES (105, "Дебальцеве, місто",5);
INSERT INTO District VALUES (106, "Дзержинськ, місто",5);
INSERT INTO District VALUES (107, "Добропільський район",5);
INSERT INTO District VALUES (108, "Донецьк, місто",5);
INSERT INTO District VALUES (109, "Дружківка, місто",5);
INSERT INTO District VALUES (110, "Єнакієве, місто",5);
INSERT INTO District VALUES (111, "Кіровське, місто",5);
INSERT INTO District VALUES (112, "Костянтинівський район",5);
INSERT INTO District VALUES (113, "Краматорськ, місто",5);
INSERT INTO District VALUES (114, "Красноармійський район",5);
INSERT INTO District VALUES (115, "Краснолиманський район",5);
INSERT INTO District VALUES (116, "Макіївка, місто",5);
INSERT INTO District VALUES (117, "Мангуський район",5);
INSERT INTO District VALUES (118, "Мар'їнський район",5);
INSERT INTO District VALUES (119, "Маріуполь, місто",5);
INSERT INTO District VALUES (120, "Новоазовський район",5);
INSERT INTO District VALUES (121, "Олександрівський район",5);
INSERT INTO District VALUES (122, "Селидове, місто",5);
INSERT INTO District VALUES (123, "Слов'янський район",5);
INSERT INTO District VALUES (124, "Сніжне, місто",5);
INSERT INTO District VALUES (125, "Старобешівський район",5);
INSERT INTO District VALUES (126, "Тельманівський район",5);
INSERT INTO District VALUES (127, "Торез, місто",5);
INSERT INTO District VALUES (128, "Харцизьк, місто",5);
INSERT INTO District VALUES (129, "Шахтарський район",5);
INSERT INTO District VALUES (130, "Ясинуватський район",5);

# 6. Житомирська область
INSERT INTO District VALUES(131,"Андрушівський район",6);
INSERT INTO District VALUES(132,"Баранівський район",6);
INSERT INTO District VALUES(133,"Бердичівський район",6);
INSERT INTO District VALUES(134,"Брусилівський район",6);
INSERT INTO District VALUES(135,"Володарсько-Волинський район",6);
INSERT INTO District VALUES(136,"Дзержинський район",6);
INSERT INTO District VALUES(137,"Ємільчинський район",6);
INSERT INTO District VALUES(138,"Житомир, місто",6);
INSERT INTO District VALUES(139,"Житомирський район",6);
INSERT INTO District VALUES(140,"Коростенський район",6);
INSERT INTO District VALUES(141,"Коростишівський район",6);
INSERT INTO District VALUES(142,"Лугинський район",6);
INSERT INTO District VALUES(143,"Любарський район",6);
INSERT INTO District VALUES(144,"Малинський район",6);
INSERT INTO District VALUES(145,"Народицький район",6);
INSERT INTO District VALUES(146,"Новоград-Волинський район",6);
INSERT INTO District VALUES(147,"Овруцький район",6);
INSERT INTO District VALUES(148,"Олевський район",6);
INSERT INTO District VALUES(149,"Попільнянський район",6);
INSERT INTO District VALUES(150,"Радомишльський район",6);
INSERT INTO District VALUES(151,"Ружинський район",6);
INSERT INTO District VALUES(152,"Червоноармійський район",6);
INSERT INTO District VALUES(153,"Черняхівський район",6);
INSERT INTO District VALUES(154,"Чуднівський район",6);

# 7. Закарпатська область
INSERT INTO District VALUES(155,"Берегівський район",7);
INSERT INTO District VALUES(156,"Великоберезнянський район",7);
INSERT INTO District VALUES(157,"Виноградівський район",7);
INSERT INTO District VALUES(158,"Воловецький район",7);
INSERT INTO District VALUES(159,"Іршавський район",7);
INSERT INTO District VALUES(160,"Міжгірський район",7);
INSERT INTO District VALUES(161,"Мукачівський район",7);
INSERT INTO District VALUES(162,"Перечинський район",7);
INSERT INTO District VALUES(163,"Рахівський район",7);
INSERT INTO District VALUES(164,"Свалявський район",7);
INSERT INTO District VALUES(165,"Тячівський район",7);
INSERT INTO District VALUES(166,"Ужгород, місто",7);
INSERT INTO District VALUES(167,"Ужгородський район",7);
INSERT INTO District VALUES(168,"Хустський район",7);
INSERT INTO District VALUES(169,"Чоп, місто",7);

# 8. Запорізька область
INSERT INTO District VALUES(170,"Бердянський район",8);
INSERT INTO District VALUES(171,"Василівський район",8);
INSERT INTO District VALUES(172,"Великобілозерський район",8);
INSERT INTO District VALUES(173,"Веселівський район",8);
INSERT INTO District VALUES(174,"Вільнянський район",8);
INSERT INTO District VALUES(175,"Гуляйпільський район",8);
INSERT INTO District VALUES(176,"Енергодар, місто",8);
INSERT INTO District VALUES(177,"Запоріжжя, місто",8);
INSERT INTO District VALUES(178,"Запорізький район",8);
INSERT INTO District VALUES(179,"Кам'янсько-Дніпровський район",8);
INSERT INTO District VALUES(180,"Куйбишевський район",8);
INSERT INTO District VALUES(181,"Мелітопольський район",8);
INSERT INTO District VALUES(182,"Михайлівський район",8);
INSERT INTO District VALUES(183,"Новомиколаївський район",8);
INSERT INTO District VALUES(184,"Оріхівський район",8);
INSERT INTO District VALUES(185,"Пологівський район",8);
INSERT INTO District VALUES(186,"Приазовський район",8);
INSERT INTO District VALUES(187,"Приморський район",8);
INSERT INTO District VALUES(188,"Розівський район",8);
INSERT INTO District VALUES(189,"Токмацький район",8);
INSERT INTO District VALUES(190,"Чернігівський район",8);
INSERT INTO District VALUES(191,"Якимівський район",8);

# 9. Івано-Франківська область
INSERT INTO District VALUES(192,"Богородчанський район",9);
INSERT INTO District VALUES(193,"Болехівський район",9);
INSERT INTO District VALUES(194,"Верховинський район",9);
INSERT INTO District VALUES(195,"Галицький район",9);
INSERT INTO District VALUES(196,"Городенківський район",9);
INSERT INTO District VALUES(197,"Долинський район",9);
INSERT INTO District VALUES(198,"Івано-Франківськ, місто",9);
INSERT INTO District VALUES(199,"Калуський район",9);
INSERT INTO District VALUES(200,"Коломийський район",9);
INSERT INTO District VALUES(201,"Косівський район",9);
INSERT INTO District VALUES(202,"Надвірнянський район",9);
INSERT INTO District VALUES(203,"Рогатинський район",9);
INSERT INTO District VALUES(204,"Рожнятівський район",9);
INSERT INTO District VALUES(205,"Снятинський район",9);
INSERT INTO District VALUES(206,"Тисменицький район",9);
INSERT INTO District VALUES(207,"Тлумацький район",9);
INSERT INTO District VALUES(208,"Яремча, місто",9);

# 11. Київська область
INSERT INTO District VALUES(209,"Баришівський район",11);
INSERT INTO District VALUES(210,"Білоцерквівський район",11);
INSERT INTO District VALUES(211,"Богуславський район",11);
INSERT INTO District VALUES(212,"Бориспільський район",11);
INSERT INTO District VALUES(213,"Бородянський район",11);
INSERT INTO District VALUES(214,"Броварський район",11);
INSERT INTO District VALUES(215,"Васильківський район",11);
INSERT INTO District VALUES(216,"Вишгородський район",11);
INSERT INTO District VALUES(217,"Володарський район",11);
INSERT INTO District VALUES(218,"Згурівський район",11);
INSERT INTO District VALUES(219,"Іванківський район",11);
INSERT INTO District VALUES(220,"Ірпінь, місто",11);
INSERT INTO District VALUES(221,"Кагарлицький район",11);
INSERT INTO District VALUES(222,"Києво-Святошинський район",11);
INSERT INTO District VALUES(223,"Макарівський район",11);
INSERT INTO District VALUES(224,"Миронівський район",11);
INSERT INTO District VALUES(225,"Обухівський район",11);
INSERT INTO District VALUES(226,"Переяслав-Хмельницький район",11);
INSERT INTO District VALUES(227,"Поліський район",11);
INSERT INTO District VALUES(228,"Рокитнянський район",11);
INSERT INTO District VALUES(229,"Сквирський район",11);
INSERT INTO District VALUES(230,"Славутич, місто",11);
INSERT INTO District VALUES(231,"Ставищенський район",11);
INSERT INTO District VALUES(232,"Таращанський район",11);
INSERT INTO District VALUES(233,"Тетіївський район",11);
INSERT INTO District VALUES(234,"Фастівський район",11);
INSERT INTO District VALUES(235,"Яготинський район",11);

# 12. Кіровоградська область
INSERT INTO District VALUES(236,"Бобринецький район",12);
INSERT INTO District VALUES(237,"Вільшанський район",12);
INSERT INTO District VALUES(238,"Гайворонський район",12);
INSERT INTO District VALUES(239,"Голованівський район",12);
INSERT INTO District VALUES(240,"Добровеличківський район",12);
INSERT INTO District VALUES(241,"Долинський район",12);
INSERT INTO District VALUES(242,"Знам'янський район",12);
INSERT INTO District VALUES(243,"Кіровоград, місто",12);
INSERT INTO District VALUES(244,"Кіровоградський район",12);
INSERT INTO District VALUES(245,"Компаніївський район",12);
INSERT INTO District VALUES(246,"Маловисківський район",12);
INSERT INTO District VALUES(247,"Новгородківський район",12);
INSERT INTO District VALUES(248,"Новоархангельський район",12);
INSERT INTO District VALUES(249,"Новомиргородський район",12);
INSERT INTO District VALUES(250,"Новоукраїнський район",12);
INSERT INTO District VALUES(251,"Олександрівський район",12);
INSERT INTO District VALUES(252,"Олександрійський район",12);
INSERT INTO District VALUES(253,"Онуфріївський район",12);
INSERT INTO District VALUES(254,"Петрівський район",12);
INSERT INTO District VALUES(255,"Світловодський район",12);
INSERT INTO District VALUES(256,"Ульяновський район",12);
INSERT INTO District VALUES(257,"Устинівський район",12);

# 13. Луганська область
INSERT INTO District VALUES(258,"Алчевськ, місто",13);
INSERT INTO District VALUES(259,"Антрацитівський район",13);
INSERT INTO District VALUES(260,"Біловодський район",13);
INSERT INTO District VALUES(261,"Білокуракинський район",13);
INSERT INTO District VALUES(262,"Брянка, місто",13);
INSERT INTO District VALUES(263,"Кіровськ, місто",13);
INSERT INTO District VALUES(264,"Краснодонський район",13);
INSERT INTO District VALUES(265,"Красний Луч, місто",13);
INSERT INTO District VALUES(266,"Кремінський район",13);
INSERT INTO District VALUES(267,"Лисичанськ, місто",13);
INSERT INTO District VALUES(268,"Луганськ, місто",13);
INSERT INTO District VALUES(269,"Лутугинський район",13);
INSERT INTO District VALUES(270,"Марківський район",13);
INSERT INTO District VALUES(271,"Міловський район",13);
INSERT INTO District VALUES(272,"Новоайдарський район",13);
INSERT INTO District VALUES(273,"Новопсковський район",13);
INSERT INTO District VALUES(274,"Первомайськ, місто",13);
INSERT INTO District VALUES(275,"Перевальський район",13);
INSERT INTO District VALUES(276,"Попаснянський район",13);
INSERT INTO District VALUES(277,"Ровеньки, місто",13);
INSERT INTO District VALUES(278,"Рубіжне, місто",13);
INSERT INTO District VALUES(279,"Сватівський район",13);
INSERT INTO District VALUES(280,"Свердловський район",13);
INSERT INTO District VALUES(281,"Сіверськодонецьк, місто",13);
INSERT INTO District VALUES(282,"Слов'яносербський район",13);
INSERT INTO District VALUES(283,"Станично-Луганський район",13);
INSERT INTO District VALUES(284,"Старобільський район",13);
INSERT INTO District VALUES(285,"Стаханов, місто",13);
INSERT INTO District VALUES(286,"Троїцький район",13);

# 14. Львівська область
INSERT INTO District VALUES(287,"Борислав, місто",14);
INSERT INTO District VALUES(288,"Бродівський район",14);
INSERT INTO District VALUES(289,"Буський район",14);
INSERT INTO District VALUES(290,"Городоцький район",14);
INSERT INTO District VALUES(291,"Дрогобицький район",14);
INSERT INTO District VALUES(292,"Жидачівський район",14);
INSERT INTO District VALUES(293,"Жовківський район",14);
INSERT INTO District VALUES(294,"Золочівський район",14);
INSERT INTO District VALUES(295,"Кам'янсько-Бузький",14);
INSERT INTO District VALUES(296,"Львів, місто",14);
INSERT INTO District VALUES(297,"Миколаївський район",14);
INSERT INTO District VALUES(298,"Мостиський район",14);
INSERT INTO District VALUES(299,"Перемишлянський район",14);
INSERT INTO District VALUES(300,"Пустомитівський район",14);
INSERT INTO District VALUES(301,"Радехівський район",14);
INSERT INTO District VALUES(302,"Самбірський район",14);
INSERT INTO District VALUES(303,"Сколівський район",14);
INSERT INTO District VALUES(304,"Сокальський район",14);
INSERT INTO District VALUES(305,"Старосамбірський район",14);
INSERT INTO District VALUES(306,"Стрийський район",14);
INSERT INTO District VALUES(307,"Трускавець, місто",14);
INSERT INTO District VALUES(308,"Турківський район",14);
INSERT INTO District VALUES(309,"Червоноград, місто",14);
INSERT INTO District VALUES(310,"Яворівський район",14);

# 15. Миколаївська область
INSERT INTO District VALUES(311,"Арбузинський район",15);
INSERT INTO District VALUES(312,"Баштанський район",15);
INSERT INTO District VALUES(313,"Березанський район",15);
INSERT INTO District VALUES(314,"Березнегуватський район",15);
INSERT INTO District VALUES(315,"Братський район",15);
INSERT INTO District VALUES(316,"Веселинівський район",15);
INSERT INTO District VALUES(317,"Вознесенський район",15);
INSERT INTO District VALUES(318,"Врадіївський район",15);
INSERT INTO District VALUES(319,"Доманівський район",15);
INSERT INTO District VALUES(320,"Єланецький район",15);
INSERT INTO District VALUES(321,"Жовтневий район",15);
INSERT INTO District VALUES(322,"Казанківський район",15);
INSERT INTO District VALUES(323,"Кривоозерський район",15);
INSERT INTO District VALUES(324,"Миколаїв, місто",15);
INSERT INTO District VALUES(325,"Миколаївський район",15);
INSERT INTO District VALUES(326,"Новобузький район",15);
INSERT INTO District VALUES(327,"Новоодеський район",15);
INSERT INTO District VALUES(328,"Очаківський район",15);
INSERT INTO District VALUES(329,"Первомайський район",15);
INSERT INTO District VALUES(330,"Снігурівський район",15);
INSERT INTO District VALUES(331,"Южноукраїнськ, місто",15);

# 16. Одеська область
INSERT INTO District VALUES(332,"Ананьївський район",16);
INSERT INTO District VALUES(333,"Арцизький район",16);
INSERT INTO District VALUES(334,"Балтський район",16);
INSERT INTO District VALUES(335,"Березівський район",16);
INSERT INTO District VALUES(336,"Білгород-Дністровський район",16);
INSERT INTO District VALUES(337,"Біляївський район",16);
INSERT INTO District VALUES(338,"Болградський район",16);
INSERT INTO District VALUES(339,"Великомихайлівський район",16);
INSERT INTO District VALUES(340,"Іванівський район",16);
INSERT INTO District VALUES(341,"Ізмаїльський район",16);
INSERT INTO District VALUES(342,"Іллічівськ, місто",16);
INSERT INTO District VALUES(343,"Кілійський район",16);
INSERT INTO District VALUES(344,"Кодимський район",16);
INSERT INTO District VALUES(345,"Комінтернівський район",16);
INSERT INTO District VALUES(346,"Котовський район",16);
INSERT INTO District VALUES(347,"Красноокнянський район",16);
INSERT INTO District VALUES(348,"Любашівський район",16);
INSERT INTO District VALUES(349,"Миколаївський район",16);
INSERT INTO District VALUES(350,"Овідіопольський район",16);
INSERT INTO District VALUES(351,"Одеса, місто",16);
INSERT INTO District VALUES(352,"Ренійський район",16);
INSERT INTO District VALUES(353,"Роздільнянський район",16);
INSERT INTO District VALUES(354,"Савранський район",16);
INSERT INTO District VALUES(355,"Саратський район",16);
INSERT INTO District VALUES(356,"Тарутинський район",16);
INSERT INTO District VALUES(357,"Татарбунарський район",16);
INSERT INTO District VALUES(358,"Фрунзівський район",16);
INSERT INTO District VALUES(359,"Ширяївський район",16);

# 17. Полтавська область
INSERT INTO District VALUES(360,"Великобагачанський район",17);
INSERT INTO District VALUES(361,"Гадяцький район",17);
INSERT INTO District VALUES(362,"Глобинський район",17);
INSERT INTO District VALUES(363,"Гребінківський район",17);
INSERT INTO District VALUES(364,"Диканський район",17);
INSERT INTO District VALUES(365,"Зіньківський район",17);
INSERT INTO District VALUES(366,"Карлівський район",17);
INSERT INTO District VALUES(367,"Кобеляцький район",17);
INSERT INTO District VALUES(368,"Козельщинський район",17);
INSERT INTO District VALUES(369,"Комсомольськ, місто",17);
INSERT INTO District VALUES(370,"Котелевський район",17);
INSERT INTO District VALUES(371,"Кременчук, місто",17);
INSERT INTO District VALUES(372,"Кременчуцький район",17);
INSERT INTO District VALUES(373,"Лохвицький район",17);
INSERT INTO District VALUES(374,"Лубенський район",17);
INSERT INTO District VALUES(375,"Машівський район",17);
INSERT INTO District VALUES(376,"Миргородський район",17);
INSERT INTO District VALUES(377,"Новосанжарський район",17);
INSERT INTO District VALUES(378,"Оржицький район",17);
INSERT INTO District VALUES(379,"Пирятинський район",17);
INSERT INTO District VALUES(380,"Полтава, місто",17);
INSERT INTO District VALUES(381,"Полтавський район",17);
INSERT INTO District VALUES(382,"Решетилівський район",17);
INSERT INTO District VALUES(383,"Семенівський район",17);
INSERT INTO District VALUES(384,"Хорольський район",17);
INSERT INTO District VALUES(385,"Чорнухинський район",17);
INSERT INTO District VALUES(386,"Чутівський район",17);
INSERT INTO District VALUES(387,"Шишацький район",17);

# 18. Рівненська область
INSERT INTO District VALUES(388,"Березнівський район",18);
INSERT INTO District VALUES(389,"Володимирецький район",18);
INSERT INTO District VALUES(390,"Гощанський район",18);
INSERT INTO District VALUES(391,"Демидівський район",18);
INSERT INTO District VALUES(392,"Дубнівський район",18);
INSERT INTO District VALUES(393,"Дубровицький район",18);
INSERT INTO District VALUES(394,"Зарічненський район",18);
INSERT INTO District VALUES(395,"Здолбунівський район",18);
INSERT INTO District VALUES(396,"Корецький район",18);
INSERT INTO District VALUES(397,"Костопільський район",18);
INSERT INTO District VALUES(398,"Кузнецовськ, місто",18);
INSERT INTO District VALUES(399,"Млинівський район",18);
INSERT INTO District VALUES(400,"Острозький район",18);
INSERT INTO District VALUES(401,"Радивилівський район",18);
INSERT INTO District VALUES(402,"Рівне, місто",18);
INSERT INTO District VALUES(403,"Рівненський район",18);
INSERT INTO District VALUES(404,"Рокитнівський район",18);
INSERT INTO District VALUES(405,"Сарненський район",18);

# 20. Сумська область
INSERT INTO District VALUES(406,"Білопільський район",20);
INSERT INTO District VALUES(407,"Буринський район",20);
INSERT INTO District VALUES(408,"Великописарівський район",20);
INSERT INTO District VALUES(409,"Глухівський район",20);
INSERT INTO District VALUES(410,"Конотопський район",20);
INSERT INTO District VALUES(411,"Краснопільський район",20);
INSERT INTO District VALUES(412,"Кролевецький район",20);
INSERT INTO District VALUES(413,"Лебединський район",20);
INSERT INTO District VALUES(414,"Липоводолинський район",20);
INSERT INTO District VALUES(415,"Недригайлівський район",20);
INSERT INTO District VALUES(416,"Охтирський район",20);
INSERT INTO District VALUES(417,"Путивльський район",20);
INSERT INTO District VALUES(418,"Роменський район",20);
INSERT INTO District VALUES(419,"Середино-Будський район",20);
INSERT INTO District VALUES(420,"Суми, місто",20);
INSERT INTO District VALUES(421,"Сумський район",20);
INSERT INTO District VALUES(422,"Тростянецький район",20);
INSERT INTO District VALUES(423,"Шосткинський район",20);
INSERT INTO District VALUES(424,"Ямпільський район",20);

# 21. Тернопільська область
INSERT INTO District VALUES(425,"Бережанський район",21);
INSERT INTO District VALUES(426,"Борщівський район",21);
INSERT INTO District VALUES(427,"Бучацький район",21);
INSERT INTO District VALUES(428,"Гусятинський район",21);
INSERT INTO District VALUES(429,"Заліщицький район",21);
INSERT INTO District VALUES(430,"Збаразький район",21);
INSERT INTO District VALUES(431,"Зборівський район",21);
INSERT INTO District VALUES(432,"Козівський район",21);
INSERT INTO District VALUES(433,"Кременецький район",21);
INSERT INTO District VALUES(434,"Лановецький район",21);
INSERT INTO District VALUES(435,"Монастириський район",21);
INSERT INTO District VALUES(436,"Підволочиський район",21);
INSERT INTO District VALUES(437,"Підгаєцький район",21);
INSERT INTO District VALUES(438,"Теребовлянський район",21);
INSERT INTO District VALUES(439,"Тернопіль, місто",21);
INSERT INTO District VALUES(440,"Тернопільський район",21);
INSERT INTO District VALUES(441,"Чортківський район",21);
INSERT INTO District VALUES(442,"Шумський район",21);

# 22. Харківська область
INSERT INTO District VALUES(443,"Балаклійський район",22);
INSERT INTO District VALUES(444,"Барвінківський район",22);
INSERT INTO District VALUES(445,"Близнюківський район",22);
INSERT INTO District VALUES(446,"Богодухівський район",22);
INSERT INTO District VALUES(447,"Борівський район",22);
INSERT INTO District VALUES(448,"Валківський район",22);
INSERT INTO District VALUES(449,"Великобурлуцький район",22);
INSERT INTO District VALUES(450,"Вовчанський район",22);
INSERT INTO District VALUES(451,"Дворічанський район",22);
INSERT INTO District VALUES(452,"Дергачівський район",22);
INSERT INTO District VALUES(453,"Зачепилівський район",22);
INSERT INTO District VALUES(454,"Зміївський район",22);
INSERT INTO District VALUES(455,"Золочівський район",22);
INSERT INTO District VALUES(456,"Ізюмський район",22);
INSERT INTO District VALUES(457,"Кегичівський район",22);
INSERT INTO District VALUES(458,"Коломацький район",22);
INSERT INTO District VALUES(459,"Красноградський район",22);
INSERT INTO District VALUES(460,"Краснокутський район",22);
INSERT INTO District VALUES(461,"Куп'янський район",22);
INSERT INTO District VALUES(462,"Лозівський район",22);
INSERT INTO District VALUES(463,"Нововодолазький район",22);
INSERT INTO District VALUES(464,"Первомайський район",22);
INSERT INTO District VALUES(465,"Печенізький район",22);
INSERT INTO District VALUES(466,"Сахновщинський район",22);
INSERT INTO District VALUES(467,"Харків, місто",22);
INSERT INTO District VALUES(468,"Харківський район",22);
INSERT INTO District VALUES(469,"Чугуївський район",22);
INSERT INTO District VALUES(470,"Шевченківський район",22);

# 23. Херсонська область
INSERT INTO District VALUES(471,"Бериславський район",23);
INSERT INTO District VALUES(472,"Білозерський район",23);
INSERT INTO District VALUES(473,"Великолепетиський район",23);
INSERT INTO District VALUES(474,"Великоолександрівський район",23);
INSERT INTO District VALUES(475,"Верхньорогачицький район",23);
INSERT INTO District VALUES(476,"Високопільський район",23);
INSERT INTO District VALUES(477,"Генічеський район",23);
INSERT INTO District VALUES(478,"Голопристанський район",23);
INSERT INTO District VALUES(479,"Горностаївський район",23);
INSERT INTO District VALUES(480,"Іванівський район",23);
INSERT INTO District VALUES(481,"Каланчацький район",23);
INSERT INTO District VALUES(482,"Каховський район",23);
INSERT INTO District VALUES(483,"Нижньосірогозький район",23);
INSERT INTO District VALUES(484,"Нова Каховка, місто",23);
INSERT INTO District VALUES(485,"Нововоронцовський район",23);
INSERT INTO District VALUES(486,"Новотроїцький район",23);
INSERT INTO District VALUES(487,"Скадовський район",23);
INSERT INTO District VALUES(488,"Херсон, місто",23);
INSERT INTO District VALUES(489,"Цюрупинський район",23);
INSERT INTO District VALUES(490,"Чаплинський район",23);

# 24. Хмельницька область
INSERT INTO District VALUES(491,"Білогірський район",24);
INSERT INTO District VALUES(492,"Віньковецький район",24);
INSERT INTO District VALUES(493,"Волочиський район",24);
INSERT INTO District VALUES(494,"Городоцький район",24);
INSERT INTO District VALUES(495,"Деражнянський район",24);
INSERT INTO District VALUES(496,"Дунаєвецький район",24);
INSERT INTO District VALUES(497,"Ізяславський район",24);
INSERT INTO District VALUES(498,"Кам'янець-Подільський район",24);
INSERT INTO District VALUES(499,"Красилівський район",24);
INSERT INTO District VALUES(500,"Летичівський район",24);
INSERT INTO District VALUES(501,"Нетішин, місто",24);
INSERT INTO District VALUES(502,"Новоушицький район",24);
INSERT INTO District VALUES(503,"Полонський район",24);
INSERT INTO District VALUES(504,"Славутський район",24);
INSERT INTO District VALUES(505,"Старокостянтинівський район",24);
INSERT INTO District VALUES(506,"Старосинявський район",24);
INSERT INTO District VALUES(507,"Теофіпольський район",24);
INSERT INTO District VALUES(508,"Хмельницький, місто",24);
INSERT INTO District VALUES(509,"Хмельницький район",24);
INSERT INTO District VALUES(510,"Чемеровецький район",24);
INSERT INTO District VALUES(511,"Шепетівський район",24);
INSERT INTO District VALUES(512,"Ярмолинецький район",24);

# 25. Черкаська область
INSERT INTO District VALUES(513,"Городищенський район",25);
INSERT INTO District VALUES(514,"Драбівський район",25);
INSERT INTO District VALUES(515,"Жашківський район",25);
INSERT INTO District VALUES(516,"Звенигородський район",25);
INSERT INTO District VALUES(517,"Золотоніський район",25);
INSERT INTO District VALUES(518,"Кам'янський район",25);
INSERT INTO District VALUES(519,"Канівський район",25);
INSERT INTO District VALUES(520,"Катеринопільський район",25);
INSERT INTO District VALUES(521,"Корсунь-Шевченківський район",25);
INSERT INTO District VALUES(522,"Лисянський район",25);
INSERT INTO District VALUES(523,"Маньківський район",25);
INSERT INTO District VALUES(524,"Монастирищенський район",25);
INSERT INTO District VALUES(525,"Смілянський район",25);
INSERT INTO District VALUES(526,"Тальнівський район",25);
INSERT INTO District VALUES(527,"Уманський район",25);
INSERT INTO District VALUES(528,"Христинівський район",25);
INSERT INTO District VALUES(529,"Черкаси, місто",25);
INSERT INTO District VALUES(530,"Черкаський район",25);
INSERT INTO District VALUES(531,"Чигиринський район",25);
INSERT INTO District VALUES(532,"Чорнобаївський район",25);
INSERT INTO District VALUES(533,"Шполянський район",25);

# 26. Чернівецька область
INSERT INTO District VALUES(534,"Вижницький район",26);
INSERT INTO District VALUES(535,"Герцаївський район",26);
INSERT INTO District VALUES(536,"Глибоцький район",26);
INSERT INTO District VALUES(537,"Заставнівський район",26);
INSERT INTO District VALUES(538,"Кельменецький район",26);
INSERT INTO District VALUES(539,"Кіцманський район",26);
INSERT INTO District VALUES(540,"Новоселицький район",26);
INSERT INTO District VALUES(541,"Путильський район",26);
INSERT INTO District VALUES(542,"Сокирянський район",26);
INSERT INTO District VALUES(543,"Сторожинецький район",26);
INSERT INTO District VALUES(544,"Хотинський район",26);
INSERT INTO District VALUES(545,"Чернівці, місто",26);

# 27. Чернігівська область
INSERT INTO District VALUES(546,"Бахмацький район",27);
INSERT INTO District VALUES(547,"Бобровицький район",27);
INSERT INTO District VALUES(548,"Борзнянський район",27);
INSERT INTO District VALUES(549,"Варвинський район",27);
INSERT INTO District VALUES(550,"Городнянський район",27);
INSERT INTO District VALUES(551,"Ічнянський район",27);
INSERT INTO District VALUES(552,"Козелецький район",27);
INSERT INTO District VALUES(553,"Коропський район",27);
INSERT INTO District VALUES(554,"Корюківський район",27);
INSERT INTO District VALUES(555,"Куликівський район",27);
INSERT INTO District VALUES(556,"Менський район",27);
INSERT INTO District VALUES(557,"Ніжинський район",27);
INSERT INTO District VALUES(558,"Новгород-Сіверський район",27);
INSERT INTO District VALUES(559,"Носівський район",27);
INSERT INTO District VALUES(560,"Прилуцький район",27);
INSERT INTO District VALUES(561,"Ріпкинський район",27);
INSERT INTO District VALUES(562,"Семенівський район",27);
INSERT INTO District VALUES(563,"Сосницький район",27);
INSERT INTO District VALUES(564,"Срібнянський район",27);
INSERT INTO District VALUES(565,"Талалаївський район",27);
INSERT INTO District VALUES(566,"Чернігів, місто",27);
INSERT INTO District VALUES(567,"Чернігівський район",27);
INSERT INTO District VALUES(568,"Щорський район",27);
