# FILL REGIONS
INSERT INTO Region VALUES (1, "Автономна республіка Крим");
INSERT INTO Region VALUES (2, "Вінницька область");
INSERT INTO Region VALUES (3, "Волинська область");
INSERT INTO Region VALUES (4, "Дніпропетровська область");
INSERT INTO Region VALUES (5, "Донецька область");
INSERT INTO Region VALUES (6, "Житомирська область");
INSERT INTO Region VALUES (7, "Закарпатська область");
INSERT INTO Region VALUES (8, "Запорізька область");
INSERT INTO Region VALUES (9, "Івано-Франківська область");
INSERT INTO Region VALUES (10, "Київ, місто");
INSERT INTO Region VALUES (11, "Київська область");
INSERT INTO Region VALUES (12, "Кіровоградська область");
INSERT INTO Region VALUES (13, "Луганська область");
INSERT INTO Region VALUES (14, "Львівська область");
INSERT INTO Region VALUES (15, "Миколаївська область");
INSERT INTO Region VALUES (16, "Одеська область");
INSERT INTO Region VALUES (17, "Полтавська область");
INSERT INTO Region VALUES (18, "Рівненська область");
INSERT INTO Region VALUES (19, "Севастополь, місто");
INSERT INTO Region VALUES (20, "Сумська область");
INSERT INTO Region VALUES (21, "Тернопільська область");
INSERT INTO Region VALUES (22, "Харківська область");
INSERT INTO Region VALUES (23, "Херсонська область");
INSERT INTO Region VALUES (24, "Хмельницька область");
INSERT INTO Region VALUES (25, "Черкаська область");
INSERT INTO Region VALUES (26, "Чернівецька область");
INSERT INTO Region VALUES (27, "Чернігівська область");